[package]
name = "het-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.2"
polynomial = "0.2.6"
GSL = "*"

[dependencies.nalgebra-lapack]
version = "*" # Replace the * by the latest version number.
default-features = false
features = [ "openblas" ]
